spring:
  config:
    import:
      - optional:classpath:.env[.properties]
      - optional:file:.env[.properties]

    user:
      borrowing:
        limit: 3

  # -- DB ----------------------------
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true


    mail:
      host: smtp.gmail.com
      port: 587
      username: chinarestro@gmail.com
      password: rnvorxiklunclrkz
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # -- Docker ----------------------------
  docker:
    compose:
      enabled: true
      lifecycle-management: none
      file: 'C:\\dev\\java\\partner\\docker-compose.yml'


  # -- DB Migration ----------------------------
  flyway:
    locations:
      - classpath:db/migration
    enabled: true
    baseline-on-migrate: true


  # ---------------- Security ------------------

  security:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:8080}
    cookie:
      secure: false
      http-only: false
      max-age: 180
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION:3600000}
      refresh-token:
        expiration: 36000000


